### ISSUE TITLE
Should set SameSite and Secure on cookies

### ISSUE THREAD

**Issue by nickscialli-usds** [usds/case-issue-api#57]
Just started getting the following message in the Chrome dev console. It looks like we need to start setting `SameSite=None` and `Secure` when cookie-ing the browser.

>A cookie associated with a cross-site resource at [url] was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by benwarfield-usds** [comment]
So, to be clear, if I'm reading the links right we need to fix this by February? Granted that's sooner than you'd think, but I think we can manage by then. :-)

**Comment by benwarfield-usds** [comment]
See also https://github.com/spring-projects/spring-boot/issues/15047

**Comment by benwarfield-usds** [comment]
Resolved in #106
